---
- name: install filebeat
  hosts: webservers
  become: yes
  tasks:
  - name: Download filebeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

  - name: Install filebeat
    command: dpkg -i filebeat-7.4.0-amd64.deb

  - name: filebeat-config.yml
    copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml


  - name: enable
    command: filebeat modules enable system

  - name: filebeat setup
    command: filebeat setup


  - name: Start filebeat
    command: service filebeat start
